info:
  component: Plus Service

server:
  port: 9000

spring:
  application:
    name: plus-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
