info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    addition-service: /addition/**
    subtraction-service: /subtraction/**
    multiplication-service: /multiplication/**
    division-service: /division/**
    calculator-service: /calculator/**

server:
  port: 8765

spring:
  application:
    name: zuul-server

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
