info:
  component: Subtraction Service

server:
  port: 9001

spring:
  application:
    name: subtraction-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
