info:
  component: Multiplication Service

server:
  port: 9002

spring:
  application:
    name: multiplication-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
