info:
  component: Addition Service

server:
  port: 9000

spring:
  application:
    name: addition-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
