info:
  component: Calculator Service

server:
  port: 9004

spring:
  application:
    name: calculator-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
